midiPlayer:
  #Do not change
  version: 2
  #the category of sounds
  soundCategory: music
  #check for updates
  checkVersion: true
  #File containing instrument mapping
  map: default.map
  #File containing drum machine mapping
  drum: default.drm
http_host: '127.0.0.1'
http_port: 8300